"""Cross-check: the browser and Python must agree on every shared derivation.

The personal oracle runs in JavaScript so a birth date never leaves the device, but
the tables it reads are generated by Python. If the two sides ever disagree about what
a birth date means, the site would quietly show a different fortune from the one the
tests here verify. So this drives the real personal.js through Node against vectors
produced by the Python implementation.

Skipped when Node is unavailable, since it is a convenience of the dev machine and CI
rather than a runtime dependency of the project.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from datetime import date, timedelta
from pathlib import Path

import pytest

from trungso import astrology, site

NODE = shutil.which("node")
PERSONAL_JS = Path(__file__).resolve().parents[1] / "site" / "personal.js"

pytestmark = pytest.mark.skipif(NODE is None, reason="node is not installed")

SAMPLE_BIRTHDAYS = [
    date(1930, 1, 29),   # the day before Tết 1930
    date(1930, 1, 30),   # Tết 1930 itself
    date(1968, 1, 29),   # the UTC+7 Tết Mậu Thân
    date(1984, 2, 2),
    date(1990, 1, 26),   # day before Tết 1990 - was broken by the floor bug
    date(1990, 1, 27),
    date(1995, 3, 12),
    date(1999, 12, 31),
    date(2000, 1, 1),
    date(2004, 2, 29),   # leap day
    date(2026, 2, 16),
    date(2026, 2, 17),
]
SAMPLE_NAMES = ["", "Nguyễn Quốc Đại", "Tran Thi Bich Ngoc", "Đỗ Đức Đông", "X Æ A-12"]


def _run_node(script: str) -> dict:
    result = subprocess.run(
        [NODE, "-e", script], capture_output=True, text=True, timeout=60, check=False
    )
    if result.returncode != 0:
        raise AssertionError(f"node failed:\n{result.stderr}")
    return json.loads(result.stdout)


def _harness(body: str) -> str:
    return f"""
    global.window = {{}};
    global.localStorage = {{ getItem: () => null, setItem: () => {{}}, removeItem: () => {{}} }};
    require({str(PERSONAL_JS)!r});
    const P = window.TrungsoPersonal;
    {body}
    """


@pytest.fixture(scope="module")
def astro_payload() -> dict:
    return site._astrology_payload()


def test_western_sign_matches_python():
    days = [date(1996, 1, 1) + timedelta(days=n) for n in range(366)]
    bounds = json.dumps(
        [{"month": m, "day": d, "name": n} for m, d, n in astrology.ZODIAC_BOUNDS]
    )
    got = _run_node(
        _harness(
            f"const bounds = {bounds};"
            f"const days = {json.dumps([d.isoformat() for d in days])};"
            "const out = {};"
            "for (const d of days) out[d] = P.westernSign(d, bounds);"
            "console.log(JSON.stringify(out));"
        )
    )
    expected = {d.isoformat(): astrology.western_sign(d) for d in days}
    assert got == expected


def test_life_path_matches_python():
    days = [date(1970, 1, 1) + timedelta(days=n * 37) for n in range(400)]
    got = _run_node(
        _harness(
            f"const master = {json.dumps(list(astrology.MASTER_NUMBERS))};"
            f"const days = {json.dumps([d.isoformat() for d in days])};"
            "const out = {};"
            "for (const d of days) out[d] = P.lifePathNumber(d, master);"
            "console.log(JSON.stringify(out));"
        )
    )
    expected = {d.isoformat(): astrology.life_path_number(d) for d in days}
    assert got == expected


def test_name_number_matches_python():
    got = _run_node(
        _harness(
            f"const rows = {json.dumps(list(astrology.PYTHAGOREAN_ROWS))};"
            f"const master = {json.dumps(list(astrology.MASTER_NUMBERS))};"
            f"const names = {json.dumps(SAMPLE_NAMES)};"
            "const out = {};"
            "for (const n of names) out[n] = P.nameNumber(n, rows, master);"
            "console.log(JSON.stringify(out));"
        )
    )
    expected = {name: astrology.name_number(name) for name in SAMPLE_NAMES}
    assert got == expected


def test_diacritic_stripping_matches_python():
    got = _run_node(
        _harness(
            f"const names = {json.dumps(SAMPLE_NAMES + ['đường', 'ĐỖ', 'Hồ Chí Minh'])};"
            "const out = {};"
            "for (const n of names) out[n] = P.stripDiacritics(n);"
            "console.log(JSON.stringify(out));"
        )
    )
    for name, js_value in got.items():
        assert js_value == astrology.strip_diacritics(name), name


def test_lunar_year_lookup_matches_python(astro_payload):
    """The lookup-table shortcut must place every birth date in the same lunar year
    the full Python algorithm does."""
    days = [date(1930, 1, 1) + timedelta(days=n * 53) for n in range(660)]
    got = _run_node(
        _harness(
            f"const table = {json.dumps(astro_payload['lunar_years'])};"
            f"const days = {json.dumps([d.isoformat() for d in days])};"
            "const out = {};"
            "for (const d of days) out[d] = P.lunarYearOf(d, table);"
            "console.log(JSON.stringify(out));"
        )
    )
    for iso, js_year in got.items():
        day = date.fromisoformat(iso)
        if day.year > 2034:  # table ends before the algorithm does
            continue
        assert js_year == astrology.read_fortune(day).lunar_year, iso


def test_full_fortune_matches_python(astro_payload):
    """End to end: the fortune the browser shows must equal the Python one."""
    cases = [(d, "Nguyễn Quốc Đại", "nam") for d in SAMPLE_BIRTHDAYS]
    payload = [
        {"birthDate": d.isoformat(), "name": name, "gender": gender}
        for d, name, gender in cases
    ]
    got = _run_node(
        _harness(
            f"const astro = {json.dumps(astro_payload)};"
            f"const profiles = {json.dumps(payload)};"
            "const out = profiles.map(p => P.readFortune(p, astro, '2026-08-19'));"
            "console.log(JSON.stringify(out));"
        )
    )
    for (day, name, gender), js in zip(cases, got, strict=True):
        py = astrology.read_fortune(day, name=name, gender=gender, today=date(2026, 8, 19))
        assert js["lunarYear"] == py.lunar_year, day
        assert js["canChi"] == py.can_chi, day
        assert js["animal"] == py.zodiac_animal, day
        assert js["napAm"] == py.nap_am, day
        assert js["element"] == py.element, day
        assert js["westernSign"] == py.western_sign, day
        assert js["lifePath"] == py.life_path, day
        assert js["nameNumber"] == py.name_number, day
        assert js["guardianStar"] == py.guardian_star, day
        assert js["tamHop"] == list(py.tam_hop), day
        assert js["tuHanhXung"] == list(py.tu_hanh_xung), day


def test_personal_prophecy_is_deterministic(astro_payload):
    """Same person, same draw -> same twelve numbers, exactly like the house oracle."""
    got = _run_node(
        _harness(
            f"const astro = {json.dumps(astro_payload)};"
            "const profile = {birthDate:'1995-03-12', name:'Nguyễn Quốc Đại', gender:'nam'};"
            "const game = {key:'mega645', pool:45, pick:6};"
            "const f = P.readFortune(profile, astro, '2026-08-19');"
            "const a = P.personalProphecy(profile, f, game, '01551', '2026-08-19');"
            "const b = P.personalProphecy(profile, f, game, '01551', '2026-08-19');"
            "const c = P.personalProphecy(profile, f, game, '01552', '2026-08-21');"
            "console.log(JSON.stringify({a:a.numbers, b:b.numbers, c:c.numbers,"
            " sermonA:a.sermon, sermonB:b.sermon}));"
        )
    )
    assert got["a"] == got["b"], "same inputs must produce the same numbers"
    assert got["sermonA"] == got["sermonB"]
    assert got["a"] != got["c"], "a different draw must produce different numbers"


def test_personal_prophecy_shape(astro_payload):
    got = _run_node(
        _harness(
            f"const astro = {json.dumps(astro_payload)};"
            "const out = [];"
            "for (const g of [{key:'mega645',pool:45,pick:6},{key:'power655',pool:55,pick:6}]) {"
            "  for (const b of ['1930-01-30','1990-01-27','2004-02-29','2026-02-17']) {"
            "    const profile = {birthDate:b, name:'', gender:null};"
            "    const f = P.readFortune(profile, astro, '2026-08-19');"
            "    out.push({game:g.key, pool:g.pool,"
            "      numbers:P.personalProphecy(profile, f, g, '00001', '2026-08-19').numbers});"
            "  }"
            "}"
            "console.log(JSON.stringify(out));"
        )
    )
    for entry in got:
        numbers = entry["numbers"]
        assert len(numbers) == 12, entry
        assert len(set(numbers)) == 12, entry
        assert numbers == sorted(numbers), entry
        assert all(1 <= n <= entry["pool"] for n in numbers), entry


def test_personal_scoreboard_counts_only_settled_draws():
    got = _run_node(
        _harness(
            "const picks = {"
            "  'mega645:00001': {numbers:[1,2,3,4,5,6,7,8,9,10,11,12], drawDate:'2026-01-01'},"
            "  'mega645:00002': {numbers:[1,2,3,4,5,6,7,8,9,10,11,12], drawDate:'2026-01-03'},"
            "  'power655:00001': {numbers:[1,2,3,4,5,6,7,8,9,10,11,12], drawDate:'2026-01-01'}"
            "};"
            "const draws = [{draw_id:'00001', date:'2026-01-01', main:[1,2,3,40,41,42]}];"
            "console.log(JSON.stringify("
            "  P.scorePicks(picks, {key:'mega645', pool:45, pick:6}, draws)));"
        )
    )
    assert got["scored"] == 1, "the undrawn pick must not be scored"
    assert got["hitsTotal"] == 3
    assert got["expected"] == pytest.approx(6 * 12 / 45)


def test_out_of_range_birth_date_reports_clearly(astro_payload):
    """Regression: a January birth date before Tết falls into the PREVIOUS lunar year,
    so the table must cover a year earlier than the earliest supported birth year.
    Anything genuinely outside it must raise, not return null for the caller to trip on.
    """
    got = _run_node(
        _harness(
            f"const astro = {json.dumps(astro_payload)};"
            "const out = {};"
            "for (const b of ['1930-01-29', '1900-05-05', '2099-01-01']) {"
            "  try {"
            "    out[b] = P.readFortune({birthDate:b, name:'', gender:null}, astro,"
            "      '2026-08-19').canChi;"
            "  } catch (e) { out[b] = 'ERROR:' + e.constructor.name; }"
            "}"
            "console.log(JSON.stringify(out));"
        )
    )
    # 29 Jan 1930 precedes Tết (30 Jan), so it belongs to lunar 1929 - and must resolve.
    assert got["1930-01-29"] == astrology.can_chi_of_year(1929)
    assert got["1900-05-05"].startswith("ERROR:")
    assert got["2099-01-01"].startswith("ERROR:")


def test_table_starts_before_the_earliest_birth_year():
    assert site.LUNAR_TABLE_START == site.EARLIEST_BIRTH_YEAR - 1


def test_js_digit_root_matches_python():
    got = _run_node(
        _harness(
            "const out = {};"
            "for (let n = 1; n <= 100; n++) out[n] = P.digitRoot(n);"
            "console.log(JSON.stringify(out));"
        )
    )
    from trungso.oracle import digit_root

    assert {int(k): v for k, v in got.items()} == {n: digit_root(n) for n in range(1, 101)}


def test_js_life_path_one_does_not_boost_every_number(astro_payload):
    """Same regression on the browser side: life path 1 must not select the whole pool."""
    got = _run_node(
        _harness(
            "const f = {lifePath:1, nameNumber:null, animal:'Ngọ', element:'Thủy',"
            " napAm:'Thiên Hà Thủy', westernSign:'Bảo Bình', guardianStar:null,"
            " tamHop:[], tuHanhXung:[]};"
            "const {reasons} = P.personalWeights(f, 45);"
            "const boosted = [...reasons.entries()]"
            "  .filter(([, why]) => why.some(w => w.includes('Số gốc')))"
            "  .map(([n]) => n);"
            "console.log(JSON.stringify({boosted}));"
        )
    )
    assert got["boosted"] == [1, 10, 19, 28, 37]
    assert len(got["boosted"]) < 45
